EXAMPLE/napari.yaml, npe2/_plugin_manager.py, npe2/manifest/commands.py, npe2/manifest/schema.py, tests/sample/my_plugin/napari.yaml, tests/test_npe2.py
=> Rename command command field to id.

EXAMPLE/napari.json, EXAMPLE/napari.yaml, EXAMPLE/pyproject.toml, npe2/_plugin_manager.py, npe2/manifest/schema.py, tests/sample/my_plugin/napari.yaml, tests/test_npe2.py
Most (all) keys are nouns, `contributes` is the only verb – I think, i'm
not a linguist.
I think for consistency it should be a noun as well.
I know that vscode uses contributes, so we can also decide to keep
contributes.
It may also be that the contributes feels weird to me as a non-native
speaker and that it's ok for a native one ? SO happy to not go this
route.
=> Rename contributes to contributions ?

npe2/_from_npe1.py, npe2/_plugin_manager.py, npe2/manifest/schema.py, tests/sample/my_plugin/napari.yaml
=> Change 'publisher' to 'author' (#39)

npe2/manifest/configuration.py, npe2/manifest/schema.py, npe2/manifest/themes.py, setup.cfg, tests/test_npe2.py
=> use pytomlpp, and test toml/json round trips

npe2/manifest/schema.py, npe2/manifest/utils.py, setup.cfg
mostly just need the regex.  but it's kind of nice to have a class with comparisons, so implemented that too
=> Remove semver dependency, vendor small portion

.github_changelog_generator
adds a config for using https://github.com/github-changelog-generator/github-changelog-generator
and adds changelog file for v0.1.0
=> add changelog generator config

README.md, npe2/_command_registry.py, npe2/_plugin_manager.py, npe2/manifest/_validators.py, npe2/manifest/commands.py, npe2/manifest/schema.py, tests/sample/my_plugin/napari.yaml, tests/test_npe2.py
as it sounds, it top level manifest
=> Replace entry_point with activate/deactive function

CHANGELOG.md
small changes including change to `schema_version`
will release later today
=> add changelog for v0.1.1

_docs/render.py
uses the schema in releases instead of main when building docs
=> use latest release schema for docs

_docs/example_plugin/some_module.py, _docs/templates/_npe2_readers_guide.md.jinja, _docs/templates/_npe2_sample_data_guide.md.jinja, _docs/templates/_npe2_widgets_guide.md.jinja, _docs/templates/_npe2_writers_guide.md.jinja
I ran into these while working through the plugin docs. I have some other general comments that might lead to other changes, but I though it was worth making a tiny PR to fix these first.
=> Fix some typos and dead links

.github_changelog_generator, CHANGELOG.md
will release later today assuming no objections @nclack @Carreau
=> add v0.2.0 changelog

npe2/_plugin_manager.py, npe2/io_utils.py, npe2/types.py, tests/sample/my_plugin/__init__.py, tests/test_contributions.py, tests/test_io_utils.py
From what I can tell, those are always path-or-paths from the types.
From the implementation that may vary. I think it's actually never Path,
but always str.
=> Clarify Typing.

.github/workflows/ci.yml, .pre-commit-config.yaml, _docs/render.py, npe2/_command_registry.py, npe2/_from_npe1.py, npe2/_plugin_manager.py, npe2/cli.py, npe2/manifest/_npe1_adapter.py, npe2/manifest/commands.py, npe2/manifest/package_metadata.py, npe2/manifest/schema.py, npe2/manifest/utils.py, pyproject.toml, setup.cfg, tests/conftest.py, tests/test_all_plugins.py, tests/test_conversion.py, tests/test_manifest.py, tests/test_npe1_adapter.py
no hurry on this one. but now that napari doesn't support 3.7, we can drop it here too
=> drop py3.7 & misc small reformats

README.md
=> Add doc links to README

npe2/io_utils.py
This PR relaxes `npe2.write` slightly to accept actual layer instances in addition to `FullLayerData` (i.e. from `List[FullLayerData],` to `List[Union[FullLayerData, napari.layers.Layer]]`)
In this case, `FullLayerData` is already strictly napari-specific (a three-tuple with very specific formatting) and it's easy to check if the provided object has a `as_layer_data_tuple()` method.  So it doesn't make much sense to force all callers of `npe2.write` to cast all layers to tuples
=> allow `npe2.write` to take layer instances

npe2/manifest/contributions/_menus.py
just clarifying the difference between menu `when` and command `enablement`, along with the `group` field in menus
=> Add docs clarifying menus `when` and `group`

npe2/__init__.py, npe2/cli.py, tests/test_cli.py
=> add version to cli

npe2/_plugin_manager.py
This calls `deactivate()` when disabling a plugin (ensuring that the plugin context is disposed) adds a couple clarifications  to docstings
=> feat: deactivate on disable

tests/test__io_utils.py
this should fix the race condition that periodically pops up in tests
=> run io_utils tests first

npe2/manifest/schema.py, tests/test_docs.py, tests/test_manifest.py
adds `visibility` field back to the manifest. 
closes #196
=> add visibility field

_docs/templates/_npe2_readers_guide.md.jinja, _docs/templates/_npe2_sample_data_guide.md.jinja, _docs/templates/_npe2_widgets_guide.md.jinja, _docs/templates/_npe2_writers_guide.md.jinja
Addresses https://github.com/napari/napari/issues/2274 by fixing a few broken links in the npe2 documentation.
=> Fix a few broken links

npe2/manifest/contributions/_contributions.py, npe2/manifest/contributions/_keybindings.py
uncommented the keybinding contribution code, but left certain features that are not supported yet still commented out
=> enable keybinding contribution

.github/workflows/test_conversion.yml
following main repo https://github.com/napari/napari/pull/5478
=> Switch from GabrielBB/xvfb-action to aganders3/headless-gui

src/npe2/_dynamic_plugin.py
=> Fix typo in `DynamicPlugin`

src/npe2/_inspection/_fetch.py, src/npe2/manifest/_bases.py
Fix bug reported on zulip https://napari.zulipchat.com/#narrow/stream/309872-plugins/topic/Plugins.20showing.20up.20in.20napari.20plugin.20dialogue/near/411169527
=> replace module separator with path separator

README.md
=> Fix link in readme to napari documentation

README.md
Closes #395.
All the remaining links are good.
=> Remove link that no longer exists in README
