npe2/manifest/schema.py
tests/test_npe2.py

Make sure that we prevent extra fields, in particular prevent typos,
and test more failures/valid cases, in particular the usage of
contributes instead of contributions, and having an empty contributions.

More Validation.

---

npe2/manifest/schema.py
tests/test_npe2.py

This adds validation for the display_name.
Addresses #22.
This uses a regex to limit display_name to 3-40 characters. The name beginning and end must not be whitespace or and underscore. The other characters must be "word" characters.
Play with the regex [here](https://regex101.com/r/QyanPt/1)

Add display_name validation

---

npe2/_from_npe1.py
npe2/manifest/package_metadata.py
npe2/manifest/schema.py
tests/test_npe2.py

this adds a PackageMetadata model, basically just a nicer object than the `email.message.Message` that comes from `importlib.metadata.Distribution`.
Adhere's strictly to PEP 566 and https://packaging.python.org/specifications/core-metadata/

PackageMetadata field

---

npe2/_command_registry.py
npe2/_plugin_manager.py
npe2/manifest/schema.py
tests/test_plugin_manager.py

Small improvement here: currently, `python_name` commands are imported upon plugin activation.  This PR makes it so that they are not resolved until someone calls `command_registry.get()` for the corresponding command id.

Delay import of `cmd.python_name` until needed

---

npe2/_from_npe1.py
npe2/_types.py
npe2/io_utils.py
npe2/manifest/io.py
npe2/manifest/sample_data.py
npe2/manifest/widgets.py
npe2/types.py
tests/test_io_utils.py

the parallel of hook_specifications.py for npe2.  Not sure yet were to surface/use these things, but we definitely need them somewhere.
note, this pr also makes npe2.types public

Start to make command APIs clearer

---

npe2/manifest/schema.py
tests/test_npe2.py

closes #64 
renames `manifest.engine` to `manifest.schema_version`

change engine to schema_version

---

npe2/manifest/_bases.py
npe2/manifest/schema.py

This pulls out two things from #63 that are generally useful and I'd like to get in:
1. It extracts the TOML/YAML read/write logic so that it is less intertwined with the PluginManifest fields, and so that it can be reused (this is useful for generating "sub" examples of, for instance, just a single contribution).
2. It turns off the default `sort_keys` behavior on `yaml.safe_dump`, so that keys appear in the output YAML in the order that they were declared in the model.

Extract out ImportExport logic from PluginManifest, don't sort yaml fields alphabetically

---

npe2/_plugin_manager.py
npe2/io_utils.py
npe2/manifest/contributions.py
npe2/manifest/readers.py
npe2/manifest/writers.py

`contributions/io.py`, unlike all other contributions, has two classes (readers and writers).  I frequently get tripped up by that when I'm searching files, and would like to standardize it to be like the rest

split contributions/io into readers and writers

---

tests/sample/my_plugin-1.2.3.dist-info/METADATA
tests/sample/my_plugin-1.2.3.dist-info/entry_points.txt
tests/sample/my_plugin/napari.yaml
tests/test_contributions.py
tests/test_io_utils.py
tests/test_manifest.py
tests/test_plugin_manager.py
tests/test_validations.py

To avoid confusion between packages and modules, this changes the name of the sample plugin that we test to `my-plugin` from `my_plugin` (which is the top module)

change sample plugin name from `my_plugin` to `my-plugin`

---

.gitignore
npe2/_command_registry.py
npe2/_plugin_manager.py
npe2/cli.py
npe2/manifest/_bases.py
npe2/manifest/commands.py
npe2/manifest/schema.py
npe2/manifest/utils.py
npe2/types.py
setup.cfg
tests/test_cli.py
tests/test_plugin_manager.py
tests/test_validations.py

as mentioned/requested by @jni in the conversation in #75 
This adds a method `PluginManifest.validate_imports` and a new flag to the cli `npe2 validate --imports` that checks to see that all of the `python_names` used in the manifest are importable
this also has the very nice side effect of making `npe2.manifest.utils.import_python_name` the _only_ place in the code where we import things from packages

Add option to validate python_name imports

---

npe2/_plugin_manager.py
tests/test_contributions.py

I made some changes to `iter_compatible_readers` in order to accept a list of paths.  This will now open stacks.  <s>Also,  npe2 was not being used for folders, and I made a change to handle those as well.</s>. I see that it did handle folders, I realized it was not using the npe2 reader I was testing with to read.  
Fixes #81 .

Handle list of paths in iter_compatible_reader

---

npe2/_from_npe1.py
tests/test_conversion.py

Closes #93 
Adds some logic to handle `entry_point`'s specified as a string rather than a list.
Added a test. The test was done for `setup.py` conversions since it's a little harder to make the mistake in the `cfg` format.

Make conversion robust to entry_point string entries

---

npe2/manifest/schema.py

By default `display_name` is the empty string. Client code has to coerce that to something reasonable (See napari/napari#4039).
It's a lot cleaner if we just do it here. This PR adds a rule to the `PluginManifest` root validator.

set display_name to plugin name when empty

---

npe2/__init__.py
npe2/manifest/package_metadata.py
tests/test_package_meta.py

If omitted, this will pick the min required metadata_version for PackageMetadata based on the fields used:
```py
pm = PackageMetadata(name="test", version="1.0", maintainer="bob")
assert pm.metadata_version == "1.2"  # because `maintainer` was introduced in 1.2
```

add min_ver to PackageMetadata

---

npe2/_plugin_manager.py
npe2/manifest/schema.py
setup.cfg
tests/sample/my_plugin/napari.yaml
tests/test_contributions.py
tests/test_plugin_manager.py
tests/test_validations.py

This adds:
- `PluginManager.enable`
- `PluginManager.disable`
and new signals:
- `PluginManager.events.plugins_registered`
- `PluginManager.events.activation_changed`
- `PluginManager.events.enablement_changed`
`_ContributionsIndex` has been minimized, but not completely removed, and gains a `remove_contributions` method
**ALSO**: note that this removes `discover()` from the init method.  So it must be called manually
see also https://github.com/napari/napari/pull/4086
I'm also taking the opportunity to re-order the methods and add docstrings on PluginManager (so the number of lines in this PR looks higher than it really is).  They're starting to get scattered about without much logic

Add enable disable

---

npe2/manifest/schema.py

See #100 I'm unsure if the logs message is enough or if it should pop up
a qt window.

Suggest to run npe2 validate when errors present.

---

.github/workflows/ci.yml
pytest.ini
tests/test_docs.py

Add a marker that is not ran by default, and add a CI entry to run only
this test
Alternate to #112, #111, closes #108

Separate dev test from integration test.

---

npe2/_plugin_manager.py

Looks like I unfortunately [accessed the private `plugin_manager._contrib` object in the npe2 module](https://github.com/napari/napari/blob/4c65afcab0e64d90284a1279f3b707228bb4606d/napari/plugins/_npe2.py#L255) in napari (yet another reminder that even code authors shouldn't use private variables across packages! 😂 ).
#101 modified it a bit, which means that if we were to release a new version of npe2 (which we need to for enable disable), then it would break new napari installations of v0.4.14 and v0.4.15. 
This PR adds back the line needed to maintain compatibility with older versions.
(tested on napari v0.4.14 and napari main)

add back deprecated _samples on contributions index

---

.github/workflows/ci.yml

This adds a CI test to make sure that npe2 works on the current napari main (running `pytest napari/plugins`).  could also add a step to checkout the latest release (though, not sure how to grab those tags automatically yet)

Test napari during CI

---

.github/workflows/ci.yml
npe2/_plugin_manager.py

In #101 greedy discovery of plugins was removed from the plugin manager `__init__`, which means that the user of the plugin manager (napari) should call it when it wants.  But napari <=0.4.15 didn't do that.  so this patch checks the napari version and does it for backwards compatibility.  
I yanked the 0.2.0 release and will release this as 0.2.1 today
Note, this also extends the CI napari tests to include `napari/layers` and `napari/components` as those are actually the tests that failed without this (since they were expecting napari-svg to be discovered... but it wasnt)

Fix auto-discovery of plugins for napari <= 0.4.15

---

npe2/manifest/schema.py

Since we use `manifest.name` as a string key in many places, it seems wise to prevent mutation on the name after instantiation

Disallow mutation on plugin manifest name

---

.github/workflows/ci.yml
.github/workflows/test_all_plugins.yml

in #132, I'm going to be trying to add a test for npe1 imports for all plugins, but it looks like I need the workflow to be in main in the first place, so I'm going to merge this.  All it does is add a new test workflow that runs a single test file (test_all_plugins) whenever a pr is labeled with `test-all-plugins`

Add ci to test all plugins on PR label part1

---

.pre-commit-config.yaml

Black used the private API of the `click` package which was broken in the last release:
https://github.com/psf/black/issues/2964
There are two options. Pin click version or update black. I suggest the second one. Like in napari: https://github.com/napari/napari/pull/4327
Also updated setup-cfg-fmt.

Fix plack problem on pre-commit CI

---

npe2/_plugin_manager.py
tests/test_npe1_adapter.py

This turns off discovery of npe1 plugins by defaulting, instead accepting an argument to `PluginManager.discover()` to turn on the shim.  this will make it a bit easier for napari to control this behavior, and allow us to release the current main without breaking napari

Turn off npe1 discovery by default

---

npe2/_dynamic_plugin.py

fixes #144
This fixes the breakage of napari used with PySide2 in npe2=0.2.2, just by "avoiding" using inspect.signature ... this is  super annoying bug in PySide2, that affects the ability to modify signatures of _any_ python object.  See https://github.com/napari/napari/pull/2265 for details

Avoid use of inspect.signature on CommandContribution class

---

npe2/manifest/schema.py

Changes codeblock to rst syntax (it was previously written in markdown syntax).
This eliminates errors when building the napari docs.

Fix codeblock directive in docstring

---

.github/workflows/update_changelog.yml

I'm not a ruby person I didn't managed to get the github changelog update gem to work, so why not make it a workflow that can be ran by a press of a button ?

Auto update changelog workflow

---

npe2/_plugin_manager.py
npe2/io_utils.py
npe2/manifest/contributions/_readers.py
npe2/manifest/contributions/_sample_data.py
npe2/manifest/utils.py
npe2/types.py
setup.cfg
tests/test_io_utils.py

There is a tiny bit more we can do once
napari/napari#4130 is merged and we assume a
minimal version of napari that only passes list of str to npe2 and give
it the stack=parameter as well, but it will take a couple releases
for this to be the case
Redo of #109 (was too complicated to rebase), so remade in a separate PR

Push stack=... through all the reader internal API, take II

---

.pre-commit-config.yaml
npe2/_plugin_manager.py
tests/test_contributions.py

fixes #129, ensuring that – all else being equal – writers declared earlier in a plugin's manifest have priority over later ones

Fix writer order preference

---

npe2/_dynamic_plugin.py
tests/test_tmp_plugin.py

Some stuff I find myself using with DynamicPlugin over in napari:  2 quick access properties, and a "spawn" method: a way to quickly create a second temporary plugin using the same plugin manager as a given dynamic plugin

Add minor conveniences for DynamicPlugin

---

npe2/_plugin_manager.py
npe2/manifest/contributions/__init__.py
npe2/manifest/contributions/_contributions.py
npe2/manifest/contributions/_menus.py
npe2/manifest/contributions/_submenu.py
tests/sample/my_plugin/napari.yaml
tests/test_plugin_manager.py

This reverts #160, which i think we've decided may not be the direction we want to go in after all (see discussion in #161 and related links)... primarily since we likely need plugins to be able to contribute to other plugins menus.
This is also the one thing that's causing our napari test fails.
After this: consider #175

Revert menu restriction (#160)

---

.github/workflows/ci.yml
_docs/render.py
npe2/manifest/contributions/_contributions.py

forgot to add `hide_docs` in Contributions.menus.
Actually, just realizing that since we use the schema.json from the latest release (not from main), this actually requires a new release to fix building docs on napari.  So this PR adds a new test to make sure that docs are building correctly.  (I can't remember the backstory, but the docs build test only runs on main, and it still for some reason, failed... so this adds another test that should catch it)

hide docs again in napari menus (Fix napari docs build)

---

npe2/manifest/_npe1_adapter.py
npe2/manifest/schema.py

This adds a new top level `npe1_shim` field to the schema, which will make it possible to determine whether a serialized manifest represents a shimmed npe1 plugin or not.
This also makes sure that all shim manifests have their contributions loaded before serialization 
cc @DragaDoncila

Add npe1_shim field to schema

---

npe2/manifest/_npe1_adapter.py
tests/test_npe1_adapter.py

Saving to cache with the current `cache_path` could (rarely) throw an `OSError` if the user didn't have permission to write to `/home`. We have run into this on the napari hub when working in a Docker image that only allows us to write to `/tmp`.
Since caching is just a convenience, this PR catches `OSError` on caching and fails silently.

Fail silently when caching throws OSError

---

npe2/cli.py
tests/test_cli.py

To help the hub collect manifests in json, this adds a `format` option to the parse command, and allows outputting to file:
```sh
npe2 parse some-package -o output.json
```

allow `npe2 parse` to output to file, add format option

---

.github/workflows/ci.yml
npe2/_dynamic_plugin.py
npe2/_plugin_manager.py
npe2/_pytest_plugin.py
setup.cfg
tests/test_plugin_manager.py
tests/test_pytest_plugin.py

This makes the pattern that napari is using for testing available to anyone as a pytest fixture named `npe2pm`.
~(need to add tests)~

add npe2pm TestPluginManager fixture

---

.github/workflows/test_all_plugins.yml
npe2/__init__.py
npe2/_fetch.py
npe2/cli.py
npe2/manifest/_npe1_adapter.py
npe2/manifest/_package_metadata.py
npe2/manifest/schema.py
npe2/manifest/utils.py
setup.cfg
tests/test_all_plugins.py
tests/test_cli.py
tests/test_fetch.py

~cc @DragaDoncila ... just a proof of principle at the moment... but working for a couple challenging ones, like `npe2 fetch napari-omero` (works because it doesn't try to install) and `npe2 fetch napari-clusters-plotter` (works because it creates a temporary install with `napari[all]` ... which is likely why many of the nometa group are failing)~
~The goal here is to essentially try the fastest, easiest, most direct methods first, then fall back to fully installing~
This adds a new `fetch` command to npe2 that will grab a manifest for any napari plugin listed on pypi.  This *includes* npe1 packges, which will be installed into a temporary isolated environment, imported, and indexed into an npe1 shim
```sh
╰─❯ npe2 fetch napari-omero
name: napari-omero
schema_version: 0.1.0
contributions: …
```

Add `npe2 fetch` command to cli to fetch remote manifests

---

npe2/_plugin_manager.py
npe2/plugin_manager.py
tests/test_plugin_manager.py

This adds a `dict()` method, akin to the `BaseModel.dict()` method on the manifests, that allows the state of the plugin manager to be exported, allowing for `include` and `exclude` arguments to be passed to each [manifest `dict()` method.](https://pydantic-docs.helpmanual.io/usage/exporting_models/)
This will come in handy for the `npe2 list` command line argument (#192 ) (but also provides a direct programmatic way)
```python
In [8]: pm.dict(include={'contributions'}, exclude={'contributions.commands', 'contributions.themes'})
Out[8]:
{
'plugins': {
'napari-svg': {
'contributions': {
'readers': None,
'writers': [
{'command': 'napari-svg.svg_writer', 'layer_types': ['image*', 'labels*', 'points*', 'shapes*', 'vectors*'], 'filename_extensions': ['.svg'], 'display_name': ''}
],
'widgets': …
```

Add PluginManager `dict()` method to export state of manager

---

npe2/_dynamic_plugin.py
npe2/io_utils.py
npe2/manifest/_package_metadata.py
npe2/manifest/contributions/_configuration.py
npe2/manifest/contributions/_themes.py
npe2/manifest/utils.py
npe2/types.py

We had some `from typing_extensions` imports, but didn't have it listed in our dependencies.  It's something that ends up being in almost every environment, so we didn't have any issues yet (I guess), but it should have been listed in deps.  Turns out though, that everything we were importing there is now available in python >=3.8, so this PR just changes those imports to `from typing`

Remove typing-extensions imports

---

npe2/cli.py

Just noticed that the plugin manager `.dict()` method is not inducing npe1 shim indexing like the previous direct access of `manifest.contributions` was doing.  I think that's something to look into in another PR, but this fixes it for now by explicitly forcing indexing

index npe1 stuff on `npe2 list`

---

tests/conftest.py
tests/test_cli.py

tests in #198 had a side-effect of writing cached manifests (I forgot to add the mock_cache fixture).  This PR just auto-uses the mock_cache fixture, since there's never any reason to actually write a (persistent) cache during tests.

Always mock cache in tests

---

npe2/cli.py

Fixes a bug when a dotted field name has been requested in `npe2 list` (such as `package_metadata.version`) if one of the upper level names doesn't exist (i.e. if `package_metadata` is `None`)

Fix `npe2 list` when a dotted field key is empty

---

npe2/_from_npe1.py
npe2/_setuputils.py
tests/test_conversion.py

In the compile PRs (#194, #186) I need to use/edit some of the package introspection code from `from_npe1`.  So I'm splitting that out here and making it slightly more generalizable so I can use it there

Split out `from_npe1` setuptools package inspection into new module

---

_docs/templates/_npe2_contributions.md.jinja
_docs/templates/_npe2_readers_guide.md.jinja
_docs/templates/_npe2_sample_data_guide.md.jinja
_docs/templates/_npe2_widgets_guide.md.jinja
_docs/templates/_npe2_writers_guide.md.jinja

This PR fixes several broken links in the documentation, mostly those referring to local anchors that are not well parsed by myst and need their own definitions.
This also fixes one instance where the anchor name (`contributions-sample_data`) was not correctly written from the template.

Fix documentation links

---

.github/workflows/fetch_manifests.yml
npe2/_fetch.py
npe2/cli.py
tests/test_cli.py

This will run a cron job twice a day to gather manifests and put them in the [manifests branch](https://github.com/napari/npe2/tree/manifests)
I actually don't expect this to work until it's on the main branch, so will likely merge to test.  I tested on my personal branch and it works.  It doesn't really affect any of the repo (except the addition of an `--all` flag to `npe2 fetch`)

add cron task to fetch manifests

---

npe2/manifest/_validators.py

Fixes #226, allows period in `manifest.name` field, in accordance with [PEP508](https://peps.python.org/pep-0508/#names)

fix name validator to allow periods

---

npe2/manifest/_validators.py
npe2/manifest/contributions/_commands.py
npe2/manifest/schema.py
tests/test_manifest.py

fixes and adds a test for https://github.com/napari/npe2/issues/226#issuecomment-1208095028

fix command id validation when dot in package name

---

npe2/manifest/_validators.py
npe2/manifest/schema.py
tests/sample/my_plugin/napari.yaml
tests/test_manifest.py
tests/test_validations.py

adds an icon field to the manifest, which will allow us to associate an icon with each plugin in the plugin installer

feat: add icon to manifest

---

npe2/manifest/contributions/_readers.py
npe2/manifest/contributions/_sample_data.py
npe2/manifest/contributions/_widgets.py
npe2/manifest/contributions/_writers.py
npe2/manifest/schema.py
npe2/manifest/utils.py
tests/test_manifest.py

alternative to #233 
@nclack, this implements option 1 from https://github.com/napari/npe2/pull/233#discussion_r945058646
it populates `Executable._plugin_name` during the `PluginManifest.__init__`, and falls back to option 4 if nothing has been set (i.e. if it's a one-off contribution), and then lastly, to the old period split if nothing is found to be installed

fix: alternate fix for dotted plugin_name

---

npe2/_inspection/_fetch.py
tests/test_fetch.py

adds more acceptable arguments to `npe2 fetch`, including a github or `git+http` URL, a zip url, or a direct url to a wheel or tar.gz source dist
```python
>>> fetch_manifest("napari-dv")
>>> fetch_manifest("napari-dv", "0.3.0")
>>> fetch_manifest("https://github.com/tlambert03/napari-dv")
>>> fetch_manifest("git+https://github.com/tlambert03/napari-dv.git")
>>> fetch_manifest("https://github.com/org/project/archive/refs/heads/master.zip")
>>> fetch_manifest("https://files.pythonhosted.org/.../package-0.3.0-py3-none-any.whl") 
>>> fetch_manifest("https://files.pythonhosted.org/.../package-0.3.0.tar.gz")
```

feat: add more fetch sources

---

npe2/manifest/schema.py
tests/test_validations.py

closes #236 and reverts a change from #14
While forbidding extra keys on makes for nicer validation if a plugin developer enters a field name incorrectly, it makes it so that we can't add fields to the manifest without making them backwards incompatible.  Normally, adding a field should be an easy migration in a schema, but currently it's hard. 
I'm not quite sure what we should do now to allow plugin developers to adopt new manifest keys like (`icon` or `visibility`) without making their plugins incompatible with any versions of npe2 earlier than our next release.  but this PR will help prevent that going forward.

bug: ignore extra fields on manifest

---

npe2/manifest/_validators.py
npe2/manifest/schema.py
tests/test_validations.py

The display name validation is too strict, both in terms of length and characters allowed.  It should allow things like colons, periods, etc...  This relaxes it to a string from 3-90 characters, and only restricts the possible values of the first character

fix: relax display name validation

---

npe2/manifest/schema.py

This reverts part of #38  and adds back a category field with a defined list of allowable values for use in in-app filtering.
see https://github.com/napari/npe2/pull/239#issuecomment-1214880678 below for clearer detail

feat: add category

---

npe2/cli.py
npe2/manifest/_bases.py
tests/test_fetch.py

Two test issues here:
It seems like hitting the pypi and hub api's failed to return napari-svg sometimes.  For pypi this is about 1 out of every 2 or 3 attempts.  For hub it's rarer.  Not quite sure why it's happening.  There's meaningful data in the response either way, but sometimes `napari-svg` isn't in the return. Not sure what the best fix is here. For now, I just check that the response data is non-empty.
The fetch-cli test was failing because it's looking at `napari-omero` which has a unicode red exclamation mark in it's package metadata. This causes character validation errors where the encoding of the string is unspecified. This is fixed by specifying 'utf-8' in a couple places in the pr.

fix flaky fetch tests

---

_docs/example_manifest.yaml
npe2/manifest/contributions/_themes.py
tests/sample/my_plugin/napari.yaml

While working on fixing napari themes (see [this zulip conversation](https://napari.zulipchat.com/#narrow/stream/212875-general/topic/theme.20not.20respected.20in.20qss/near/315705427)) I noticed that some fields that are available in napari are not exposed/tested here: `icon` was unused, and `syntax_style` was not exposed. I added them to the specs and description.
Also, I noticed that if you pass wrong/nonexisting keys, `npe2` does not complain. Is this intended?

Expose `syntax_style`

---

.github/workflows/ci.yml
npe2/manifest/_package_metadata.py
tests/test_package_meta.py

The `PackageMetadata` class is configured to ignore extra fields but instantiation can still fail (raises a `KeyError`) when actually provided an extra field due to this custom root validator. Based on the config this does not seem like the intended behavior.
```
class PackageMetadata(BaseModel):
....
class Config:
extra = Extra.ignore
...
@root_validator(pre=True)
def _validate_root(cls, values):
if "metadata_version" not in values:
fields = cls.__fields__
mins = {fields[n].field_info.extra.get("min_ver", "1.0") for n in values}
values["metadata_version"] = str(max(float(x) for x in mins))
return values
```
This PR just changes that validator skip over any values not in the list of expected fields during this step.

Fix PackageMetadata validation error with extra provided field

---

docs/_config.yml

Fixes one broken link in the napari documentation.
In `_docs/templates/_npe2_contributions.md.jinja` (which is used to generate https://napari.org/stable/plugins/contributions.html, the lack of correct URL for the magicgui docs inventory file will create a broken link to `magicgui.widgets.Widget` (see https://napari.org/stable/plugins/contributions.html#contributions-widgets)

Fix link to magicgui objects.inv in intersphinx

---

tests/test_fetch.py

the `testfetch_manifest_with_full_install` in `test_fetch.py` uses `assert isinstance(mf, NPE1Adapter)` for `napari-ndtiffs`:
https://github.com/napari/npe2/blob/d7329b7088f59ac743a67ff47aca32067b5a246a/tests/test_fetch.py#L72-L78
Recently, that plugin was updated to use npe2, so as a result the test fails.
See also discussion starting here: https://github.com/napari/npe2/pull/275#issuecomment-1493137069
This PR passes the `version` argument to use version 0.1.2 of the plugin which is npe1. This is the simple fix to keep the test working as it has.
However, maybe it's best to just drop that NPE1 assert, because I'm not sure it matters that the plugin is or isn't npe1—there are two specific npe1 shim tests already. 
So then here we would only assert the name and contributions.
PS. my OCD …

Fix tests: use npe1 version (0.1.2) of napari-ndtiffs

---

npe2/io_utils.py
tests/test__io_utils.py

Currently we raise the same error in `read` when no layer data is returned by any of the tried readers, regardless of whether a plugin name was given or not. This PR updates the error message to be specific when a `plugin_name` is passed.
This has the added benefit of fixing this [issue](https://github.com/ome/napari-ome-zarr/issues/86) over in `napari-ome-zarr` (which is actually a reincarnation of what napari #4026 was trying to solve) by ensuring the error is re-raised over on the `napari` side. 
I thought about whether a fix should go in `napari` instead, but I think this is the right place to fix this. Over in `napari` we would have to track somehow whether a plugin was tried or not so that we could know whether to continue with `npe1` plugins. But I think if the user chose a plugin, …

Add specific error when reader plugin was chosen but failed

---

setup.cfg

Pin pydantic to be bellow 2.0 as we know that current npe2 code is incompatible with pydatnic

Pin pydantic bellow 2.0

---

src/npe2/_pytest_plugin.py
tests/test_pytest_plugin.py

the stacklevel=2 on the `TestPluginManager` from the last precommit update is causing unnecessary warnings in the napari tests.  This converts it to a logging.warning.

fix: use logger instead of warning for TestPluginManager.discover

---

src/npe2/io_utils.py
src/npe2/manifest/utils.py
tests/test__io_utils.py

this fixes an issue wherein `npe2.read` doesn't find a command registered with a non-global PluginManager instance

fix: pass command registry to rdr.exec in io_utils._read

---

src/npe2/_plugin_manager.py
tests/test__io_utils.py

First shot at making the matching of paths to the declared extensions case insensitive.
Closes: https://github.com/napari/napari/issues/5663
Closes https://github.com/napari/npe2/issues/271
@DragaDoncila I'm not sure this is how you had it in mind?
I'm not super familiar with the code base so not sure I'm approaching it the right way vs. just bandaid bugfix.
I added two tests and make fixes to get the tests to pass.
Maybe this is too kludgey...

Bugfix: use .lower() to make paths & pattern fnmatch case  insensitive

---

_docs/render.py
pyproject.toml
src/npe2/_inspection/_setuputils.py
src/npe2/_setuptools_plugin.py
src/npe2/manifest/_bases.py
src/npe2/types.py

closes #291 by using tomli instead

remove tomlpp

---

.github/workflows/ci.yml

Workaround for problem with napari-svg problem pointed in #297.
The original bug is in repository as `("0", "1", "6") > ("0", "1", "10")` - the wrong code for version comparison.

fix: use constraints in napari tests

---

_docs/templates/_npe2_widgets_guide.md.jinja

Closes https://github.com/napari/docs/issues/186 and prevents leaking widgets in cases where widgets remain floating (undocked)

DOCS: Widget guide should consistently use parent=None kwarg in examples

---

.github/workflows/ci.yml
src/npe2/manifest/contributions/_json_schema.py

This fixes an [issue reported on Zulip](https://napari.zulipchat.com/#narrow/stream/309872-plugins/topic/napari.20plugin.20manifest.20schema/near/386669802) by @seankmartin. Basically there was a small error in the generated manifest json schema:
```
❯ check-jsonschema --check-metaschema _schema.json
Schema validation errors were encountered.
_schema.json::$.definitions.ConfigurationProperty.properties.type.anyOf[1].minItems: True is not of type 'integer'
_schema.json::$.definitions.Draft06JsonSchema.properties.type.anyOf[1].minItems: True is not of type 'integer'
_schema.json::$.definitions.Draft07JsonSchema.properties.type.anyOf[1].minItems: True is not of type 'integer'
```
The root of the problem is here, where `min_items` is set to `True` instead of an integer. …

Fix invalid JSON Schema

---

_docs/templates/_npe2_widgets_guide.md.jinja

This PR:
* Clarifies that the only supported widget parent classes are `QtWidgets.QWidget` or `magicgui.widgets.Widget`. The "such as" suggested that other parent classes could be supported
* Removes documented support for wrapper functions - going forward we do not want to support wrapper functions. (I.e. we do not want new plugins to use wrappers). it is difficult to type (both the wrapper, which will just be a normal function, and the return object, which could be many things) and is too flexible and difficult maintain.
* I think we want to be backwards compatible but this is outside the scope of this PR and should be discussed in: https://github.com/napari/napari/issues/6174 
Context - this was noted as part of the menu contributions work (https://github.com/napari/napari/issues/6174)

DOC Update and clarify supported widget contributions

---

pyproject.toml
src/npe2/_inspection/_fetch.py
src/npe2/_inspection/_full_install.py
tests/test_fetch.py

This PR updates for a couple api changes in dependencies that are blocking #311 and #312.
For the napar-hub api, the `/plugins` endpoint was removed (see [here](https://github.com/chanzuckerberg/napari-hub/discussions/1065)). This impacts the `get_hub_plugins()` function, and a test `test_get_hub_plugins` which fails without this change. It doesn't appear that anything actually uses these, so this PR removes them.
Also [build](https://github.com/pypa/build) updated to 1.0. `IsolatedEnvBuilder` was renamed to `DefaultIsolatedEnv`.

update url for fetching plugin listing from napari hub

---

.github/workflows/ci.yml
pyproject.toml
tests/test_fetch.py
tests/test_pytest_plugin.py

In this PR I have disabled the test depending on `example-plugin` python package as it was hidden by the creator.

Fix tests by disble broken one

---

src/npe2/_command_registry.py

Adds some info about when `CommandRegistry` is updated. Uses info learned when debugging https://github.com/napari/npe2/issues/314
Happy to change wording or move to a better place.

DOC Add doc in `CommandRegistry` about when it is updated

---

.github/workflows/ci.yml
.github/workflows/test_all_plugins.yml
.github/workflows/test_conversion.yml

Stop using `styfle/cancel-workflow-action` and use the builtin concurrency feature.

Use concurency for canceling workflows

---

.github/workflows/ci.yml
pyproject.toml
src/npe2/_dynamic_plugin.py
src/npe2/_pydantic_compat.py
src/npe2/implements.py
src/npe2/implements.pyi
src/npe2/manifest/_bases.py
src/npe2/manifest/_package_metadata.py
src/npe2/manifest/contributions/_commands.py
src/npe2/manifest/contributions/_configuration.py
src/npe2/manifest/contributions/_contributions.py
src/npe2/manifest/contributions/_icon.py
src/npe2/manifest/contributions/_json_schema.py
src/npe2/manifest/contributions/_keybindings.py
src/npe2/manifest/contributions/_menus.py
src/npe2/manifest/contributions/_readers.py
src/npe2/manifest/contributions/_sample_data.py
src/npe2/manifest/contributions/_submenu.py
src/npe2/manifest/contributions/_themes.py
src/npe2/manifest/contributions/_widgets.py
src/npe2/manifest/contributions/_writers.py
src/npe2/manifest/schema.py
src/npe2/manifest/utils.py
tests/test_manifest.py
tests/test_validations.py

allow to use with pydantic 2
https://github.com/napari/napari/issues/6350

Add pydantic 2 compatibility layer 

---

tests/test_fetch.py

It looks like brainreg-segment in version 0.2.19 switch to be npe2 plugin

Add constraint for brainreg-segment in test

---

.github/workflows/ci.yml

This pr fixes the bug of 403 error during create github release:
```
Run softprops/action-gh-release@v1
👩‍🏭 Creating new GitHub release for tag v0.7.4...
⚠️ GitHub release failed with status: 403
undefined
retrying... (2 retries remaining)
👩‍🏭 Creating new GitHub release for tag v0.7.4...
⚠️ GitHub release failed with status: 403
undefined
retrying... (1 retries remaining)
👩‍🏭 Creating new GitHub release for tag v0.7.4...
⚠️ GitHub release failed with status: 403
undefined
retrying... (0 retries remaining)
❌ Too many retries. Aborting...
Error: Too many retries.
```
https://github.com/softprops/action-gh-release/issues/400#issuecomment-1869045218
I have added also `id-token: write` because this is set of permissions that we have in the main repository.

Add permisions to deploy steep

---

tests/test_conversion.py

This test is failing in CIs in #340.
I think it is because there is no warning raised (not sure why the `UserWarning` is there). It used to pass because of this bug in pytest https://github.com/pytest-dev/pytest/issues/9036, but this was fixed in https://github.com/pytest-dev/pytest/pull/11129 and included in a recent release, thus our CIs are failing. 
Note that I have update the test to be more specific about the exception raised (`PackageNotFoundError`) but it is not needed, subclass exceptions are still accepted by pytest. Also added a message to be more specific.

TST Fix `test_conversion_missing`

---

src/npe2/manifest/_package_metadata.py

someone recently showed me an issue validating the manifest of a napari plugin, 
```
ValidationError: 1 validation error for PackageMetadata
metadata_version
unexpected value; permitted: '1.0', '1.1', '1.2', '2.0', '2.1', '2.2' (type=value_error.const; given=2.3; permitted=('1.0', '1.1', '1.2', '2.0', '2.1', '2.2'))
```
What happened is that PEP685 https://peps.python.org/pep-0685/ added a new spec (v2.3), and some build backends have begun to implement it.  For example, hatchling (which this package was using) bumped their default version to v2.3 5 days ago: https://github.com/pypa/hatch/commit/1a9c30dace7e811656a09b5a3ad0e03d62fb25de
This PR just relaxes the validation of metadata_version to allow for any string.  
@napari/core-devs, this is something that would be important to get in …

allow v2.3 in metadataversion, fallback to any string

---

_docs/example_plugin/some_module.py
src/npe2/types.py

https://github.com/napari/docs/pull/367#pullrequestreview-1921207030
https://github.com/napari/docs/issues/365

Adopt quotes around type names to make Reader ex. copy/paste-ready

---

_docs/templates/_npe2_widgets_guide.md.jinja

Add note that type annotations should be str to avoid having `napari` as dependency

DOC Add note on string type annotations in widget contributions

---

_docs/templates/_npe2_widgets_guide.md.jinja

Depends on https://github.com/napari/docs/pull/286 
Adds references to new 'creating widgets' section and gallery and cookiecutter to widget contributions page.

DOC Add cross references to widget contributions

---

src/npe2/_plugin_manager.py
tests/test_plugin_manager.py

Adding this dictionary to support quick mapping of widgets/commands to their menus for implementing contributable menus . Prior to this PR, you would have to search all menu contributions for the command of the contribution you were currently processing. This map allows you direct access to the menus this command needs to live in. 
This is a precursor to potentially rearchitecting the manifest schema entirely to be "command-first".

Add dictionary mapping `command_id` to its associated `MenuCommand`s for each plugin

---

src/npe2/_plugin_manager.py

Closes https://github.com/napari/napari/issues/7135
This is a naive fix. If the key doesn't exist when disabling, just return None.

On disable, dont try to pop a key that doesn't exist

---

src/npe2/types.py

We should accept any `Mapping` object as valid metadata. 
Implement https://napari.zulipchat.com/#narrow/stream/212875-general/topic/DeprecatingDict.20not.20accepted.20in.20LayerDataTuple/near/468436819

Change type of layer Metadata from Dict to Mapping

---

tests/test_fetch.py

Closes #363 by changing the plugin used in the test to avoid name normalization issues entirely.

Change npe1 plugin used for sample data test

---

_docs/templates/_npe2_widgets_guide.md.jinja

Remove mention of cookiecutter-napari-plugin from the widget guide.

Update widgets guide to point to napari-plugin-template

---

pyproject.toml
src/npe2/_inspection/_fetch.py
src/npe2/_plugin_manager.py
src/npe2/cli.py
tests/test_cli.py
tests/test_fetch.py

This PR removes all utilities and tests for fetching **all** plugins from PyPI, as the HTML scraping method is no longer valid. It keeps utilities for fetching specific manifests from PyPI.

Remove utilities for fetching all plugins

---

src/npe2/manifest/utils.py

https://bugs.debian.org/1090247 shows a napari test failure caused by this on Python 3.13.  On closer inspection I found that `/usr/lib/python3.13/dist-packages/coverage-7.6.0.egg-info` and `/usr/lib/python3.13/dist-packages/tqdm-4.67.1.dist-info` existed with no `Name` metadata field.  This shouldn't cause a failure here.

Tolerate distributions with no Name

---

_docs/templates/_npe2_readers_guide.md.jinja

Depends on [napari/#7443](https://github.com/napari/napari/pull/7443).
Extend wording in reader guide to mention the option to return instantiated `Layers` instead of just `LayerDataTuples`

Update reader guide to include option to return full `Layer` objects.

---

src/npe2/_inspection/_from_npe1.py
tests/npe1-plugin/npe1_module/__init__.py
tests/test_conversion.py

Prior to this PR, declaring multiple implementations of the same hookspec in an npe1 plugin would lead to a converted manifest with multiple commands of the same ID e.g. `plugin_name.get_reader` multiple times, or `plugin_name.write_labels` multiple times.
Even though this is technically "valid" per the schema, it should not be, because this leads to errors in trying to register the commands in napari. App-model (correctly, imo), does not allow you to register multiple commands with the same ID.
We should update the schema validator to disallow multiple declarations of the same command ID, but in the meantime, this PR disambiguates converted commands for the same hook spec by using the function name instead of the spec name.

Fix naming of npe1 converted contribution commands and add tests

---

.github/workflows/ci.yml
tests/test_fetch.py

Since we have some PRs in-flight I'm getting  CI green again by:
- skipping the test causing the failure described in #378 so that we can get CI green. In future we should find a different plugin to test.
- adding `src/` to the napari test paths

Fix CI by skipping test and adding `src/` to napari test paths

---

src/npe2/cli.py
tests/test_cli.py

This PR fixes the error box being displayed when running `npe2` without any command line options.
**Before**
**After**

Fix error box displayed when CLI launched with no options

---

src/npe2/_inspection/_fetch.py
tests/test_fetch.py

This PR tests the function and brings coverage back to green.
The test uses mocks and verifies that `_get_manifest_from_zip_url`:
- Properly uses the context manager
- Correctly finds the first directory inside the extracted path
- Passes that directory to the build function and returns its result
This PR modifies the `_get_manifest_from_zip_url` to recurse the zip beyond the first directory to look for the manifest. Keeps the original approach as a fallback if searching the zip does not find a manifest.

Add test for get manifest from zip and improve logic to recurse the zip to find manifest

---

_docs/render.py
_docs/templates/_npe2_contributions.md.jinja
src/npe2/manifest/contributions/_contributions.py
src/npe2/manifest/contributions/_submenu.py

Ok, this is a replacement for https://github.com/napari/npe2/pull/387
Instead of whack a mole I tried to go from the start looking at the schema.json (release in this repo)
```
"menus": {
"title": "Menus",
"hide_docs": true,
"type": "object",
"additionalProperties": {
"type": "array",
"items": {
"anyOf": [
{
"$ref": "#/definitions/MenuCommand"
},
{
"$ref": "#/definitions/Submenu"
}
]
}
}
},
"submenus": {
"title": "Submenus",
"hide_docs": true,
"type": "array",
"items": {
"$ref": "#/definitions/SubmenuContribution"
}
},
```
If you compare to some of the others:
```
"readers": {
"title": "Readers",
"type": "array",
"items": {
"$ref": "#/definitions/ReaderContribution"
}
},
"writers": {
"title": "Writers",
"type": "array",
"items": {
"$ref": "#/definitions/WriterContribution"
}
},
"widgets": …
```

Show menus and submenus in the contributions page
